FROM openjdk:21-jdk-buster AS build
WORKDIR /app
COPY . .
RUN chmod +x ./gradlew
RUN ./gradlew build

FROM openjdk:21
WORKDIR /app
COPY --from=build /app/build/libs/users_api_mecroservice_on_webflux-0.0.1.jar .
COPY docker-startup.sh .
RUN chmod +x docker-startup.sh
EXPOSE 8082
CMD ["./docker-startup.sh"]

